import Navbar from "@/components/nav/navbar";
import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
	title: "Supabase",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body className={`relative ${inter.className} bg-slate-50`}>
				<Navbar />
				{children}
			</body>
		</html>
	);
}
